
# Representativeness Analysis Configuration

# Path configurations
paths:
  library_dir:    # Directory containing powdersearch.py
  dataset_dir:    # Directory containing snow depth data
  output_folder:  # Directory for analysis results
  dem_path:       # Path to DEM file
  feature_layers_dir:   # Directory containing terrain feature layers
  station_locations: # CSV file with station locations

# Analysis settings
analysis:
  name: "220625"       # Name for this analysis
  years: []     # Years to include in analysis (empty for all)
  calc_yearly_stats: True                   # Calculate statistics for each year
  calc_timeseries_stats: false               # Calculate statistics for whole timeseries
  calc_deviations: false                     # Calculate deviations from global stats
  calc_station_representativeness: false     # Calculate representativeness for stations
  calc_feature_class_stats: false            # Calculate statistics per feature class
  pixel_size: 2                            # Pixel size in meters (only producing 2m right now for 2m input data)

# Station analysis settings
stations:
  buffer_radius: 250                        # Buffer radius around stations in meters
  include_stations: []                      # List of station IDs to include (empty for all)
  exclude_stations: []                      # List of station IDs to exclude

# Terrain features for class analysis
terrain_features:
  - name: "slope"
    classes: [0, 15, 30, 40, 50, 90]
    enabled: false
  - name: "aspect"
    classes: [0, 45, 135, 225, 315, 360]
    enabled: false
  - name: "elevation"
    classes: [1500, 2000, 2500, 3000, 3500, 4000]
    enabled: false
  - name: "tpi"
    classes: [-3, -1, 0, 1, 3]
    enabled: false
  - name: "curvature"
    classes: [-0.5, -0.2, 0, 0.2, 0.5]
    enabled: false
  - name: "snowdepth_mean"
    classes: [0, 1, 2, 3, 4, 5]
    enabled: false

# Visualization settings
visualization:
  colormap: "cmc.navia_r"
  snow_depth_range: [0, 5]
  diff_range: [-2, 2]
  diff_colormap: "cmc.vik_r"
  plot_timeseries: true
  plot_maps: true
  
# Processing settings
processing:
  parallel: true
  max_workers: 8  # Set to null for auto-detection
  resampling_method: "nearest"  # Options: nearest, bilinear, cubic
  
# Validation settings
validate_paths: false  # Set to false to disable path validation

# Output settings
output:
  export_csv: true
  export_tiff: true
  export_plots: true

  create_report: true
